githubschool/nov-13

- _posts/0000-01-05-iyussuf.md
My Changes to the caption file
> My Changes in the Caption

- _posts/0000-01-10-ghanashyams.md
@brianamarie  review pl.
This closes #2
> CHanged Caption GhanashyamS Slide

- _posts/0000-01-09-arvindsbabu.md
> Changing caption

- _posts/0000-01-06-jaishaunik.md
@jaishaunik Random text here.
This closes #2
> jaishaunik - Changing caption text

- _posts/0000-01-08-gharish86.md
@harish, could you please look at
> Change caption harish slide

- _posts/0000-01-20-ambpac1220.md
@mkumarkr check it out
closed #9
> Changed the caption

- _posts/0000-01-14-mkumarkr.md
#Change caption
@brianamarie could you please review
This closed #2
> Change caption mkumarkr slide

- _posts/0000-01-15-vinaymbharadwaj.md
@brianamarie I just changed some text.
This closes #8 !
> Added a caption to an image!

- _posts/0000-01-16-ibharama.md
> change caption

- _posts/0000-01-19-anjithan.md
@anjithan could you please review
This closes #2
> Change caption jithan slide

- _posts/0000-01-04-tej1599.md
@bhatchetan Could you please look at this change ??
This Closes #2
> changed the caption as my first commit

- _posts/0000-01-21-brianamarie.md
@brianamarie Could please .....
This closes #2
> Change caption brianamarie slide

- _posts/0000-01-21-shahulirshad.md
#Change  caption
@shahulirshad 
This closes #10
> Change caption shahulirshad slide

- _posts/0000-01-11-Racersclub.md
Initial commit
this closes #19
> Initial commit

- _posts/0000-01-07-bhatchetan.md
#Change caption
@tej1599 COuld you please look at this change
This is related to #2
> my first commit, changed caption

- assets/css/style.scss
> Resolving conflict

- _posts/0000-01-01-intro.md
> Editing the intro file which is common

- _posts/0000-01-04-tej1599.md
> Tejas's Changes

- _posts/0000-01-21-shahulirshad.md
> testing for conflicts

- _posts/0000-01-21-brianamarie.md
This pull request changes the brianamarie post.
> Conflict in brianamarie
